[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "gitlabber"
authors = [{name = "ezbz", email = "ezbz@github"}]
dynamic = ["version", "description"]
